# // ? should use multi-stage build to have a smaller and cleaner final image

FROM arm64v8/golang:1.20

WORKDIR /app
COPY . .
RUN go mod download
ENV CGO_ENABLED=1
RUN go build -tags=nomsgpack -o app .
EXPOSE 8080
ENV JWT_KEY="JWT_secret-key!"
CMD ["./app"]
