name: Build and Publish Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.0

      - name: Run tests
        run: go test ./...

      - name: Build Docker image
        run: |
          docker build -t ${GITHUB_REPOSITORY}:latest .

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag ${GITHUB_REPOSITORY}:latest ghcr.io/${GITHUB_REPOSITORY}:latest
          docker push ghcr.io/${GITHUB_REPOSITORY}:latest
